name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Compile
        run: mvn test-compile -pl flink-runtime -am
      - name: Test 1:
        run: mvn -pl flink-runtime test -Dtest=org.apache.flink.runtime.state.FileStateBackendMigrationTest#testKeyedMapStateStateMigration
      - name: Nondex Test
        run: mvn -pl typescript-g edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.apache.flink.runtime.state.FileStateBackendMigrationTest#testKeyedMapStateStateMigration
